### ISSUE TITLE
Categorised Elements don't export

### ISSUE THREAD

**Issue by jonhorner** [roryg/ElementHelper#46]
Elements that already exist in MODX within categories are not exported.

New elements in which are created outside MODX within sub-folders are imported and categorised though.

Using **MODX 2.5.2** and **elementhelper-2.0.0-alpha-3.transport.zip**

**Comment by roryg** [comment]
I haven't had the time to work on this for awhile so I'm not exactly sure but this is probably because of the Category Whitelist setting. If you add the categories that you want to use to the whitelist setting it should work. The setting was added to help prevent tracking elements (such as plugins) created by other Modx Extras.

**Comment by jonhorner** [comment]
Thanks for the quick reply, that was indeed the problem.
